### ISSUE TITLE
建议添加记忆胶囊可以支持PDF文件

### ISSUE THREAD

**Issue by Wooden-Gear** [wizardAEI/Gomoon#100]
一般要用到记忆胶囊的，都是相对较大的文档，或者是书籍的PDF版。
虽然有在线转换工具，但对文档大小有限制。
本地工具MD转PDF的倒是很多，PDF转MD的却都要部署，对于我这样没有编程基础的人太难了。

**Comment by wizardAEI** [comment]
哈喽，这个已经在规划啦，后续会尽量支持到和读取文件一样的级别，只不过一个人维护（在工作之余）进度确实缓慢，支持后第一时间更新👼
