### ISSUE TITLE
复制、朗读、编辑、重新生成快捷栏可以考虑对话下方也生成一个

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#102]
复制、朗读、编辑、重新生成快捷栏可以考虑对话下方也生成一个
因为一般都是对话看到最后再做操作，AI对话都比较话痨，要向上滚动几屏才能复制

**Comment by wizardAEI** [comment]
我觉得可以，目前很多对话也都是放在文本下面的，不过改动可能比较大，要考虑美观和交互，后续修改后会再次回复！

**Comment by wizardAEI** [comment]
这个版本会直接把操作移到下面，后续样式上再做微调

**Comment by wizardAEI** [comment]
哈喽，1.1.7版本已更新，目前已上架mac版本，预计周一会上架win版本👼

**Comment by lgc653** [comment]
期待周一的新版本，作为重度使用用户应该能大大降低我鼠标滚轮的磨损
