### ISSUE TITLE
v1.1.8粘贴图片到对话框，显示“正在计算token……”，然后就卡死

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#106]
粘贴图片到对话框，显示“正在计算token……”，然后就卡死
感觉应该是bug，因为我机器不应该会计算几分钟都计算不出来。

**Comment by wizardAEI** [comment]
请问发送的图片是什么格式的？

**Comment by lgc653** [comment]
直接截图后粘贴的，另存为jpg然后再传也不行

**Comment by wizardAEI** [comment]
点击上传按钮，上传图片会遇到该问题吗

**Comment by lgc653** [comment]
都不行，直接选图片和粘贴图片都不行，Windows环境

**Comment by wizardAEI** [comment]
请问平时在使用Gomoon的过程中，电脑底部的数字是会根据输入量变化的吧（在输入的同时也会变化）
![image](https://github.com/user-attachments/assets/fadb63bb-b71c-454a-8c30-8c782082c867)

**Comment by lgc653** [comment]
不会变化

**Comment by wizardAEI** [comment]
使用管理员方式启动 Gomoon，看下是否有效果呢？目前看来是Gomoon中的字数统计模块没有在你的本地正常运行

**Comment by lgc653** [comment]
也不行，我记忆中老版本好像是可以的，但是1.1.8不行

**Comment by wizardAEI** [comment]
麻烦进行如下操作：
1. 上传一个文件，点击文件进入文件夹（如果也上传不了文件，请尝试进入：C:\Users\Lenovo\AppData\Roaming\Gomoon\embedding 并跳到第三步  这里的Lenovo需要按情况改成你的用户名或电脑品牌名）
![image](https://github.com/user-attachments/assets/8075c9a7-a568-49b3-8ed2-bea5bf8f04f4)
2. 退回到文件夹上一级别，找到embedding文件夹
3. 进入Xenova，查看下方是否有如下文件（并且体积大小也都一致）：
![image](https://github.com/user-attachments/assets/d7d2caf6-e51a-4227-9547-74f62dd5b26a)

**Comment by wizardAEI** [comment]
![image](https://github.com/user-attachments/assets/165be7f1-43bf-4e2f-b77a-77b8fb402838)
详细位置

**Comment by lgc653** [comment]
Xenova目录下面只有jina-embeddings-v2-base-zh文件夹，jina-embeddings-v2-base-zh文件夹里面才有这3个文件

**Comment by wizardAEI** [comment]
请问文件大小一致吗

**Comment by lgc653** [comment]
不一致，我之前用过记忆胶囊功能

**Comment by wizardAEI** [comment]
删除整个embedding文件后，重启Gomoon，看下是否有效果

**Comment by wizardAEI** [comment]
也许是网络波动，导致当时下载这些文件时出了问题，最终导致了后续该模块异常

**Comment by lgc653** [comment]
不行，下载下来还是2,030,772 字节，而且还是不能计算token

**Comment by wizardAEI** [comment]
方便截个图吗

**Comment by wizardAEI** [comment]
文件夹部分

**Comment by lgc653** [comment]
![image](https://github.com/user-attachments/assets/c772b0dd-5334-4678-a7f9-901dc8d4939c)

**Comment by wizardAEI** [comment]
非常抱歉，问题已经查清，主要原因是因为依赖打包错误，该问题会尽快在1.1.9版本修复！

**Comment by lgc653** [comment]
太好了。期待！

**Comment by wizardAEI** [comment]
1.1.9 已更新！

**Comment by lgc653** [comment]
收到，昨晚已经用上了，谢谢
