### ISSUE TITLE
记忆胶囊支持批量导入和文件夹同步

### ISSUE THREAD

**Issue by whshang** [wizardAEI/Gomoon#109]
### 功能描述

导入md时只能一个一个导入，无法直接将obsidian的文件夹批量加入

### 如何实现

可以参考Msty的Knowledge Stacks

### 其他信息

无

**Comment by wizardAEI** [comment]
1. 哈喽，因为我没用过 obsidian 所以想了解下，obsidian 可以批量导出 markdown 吗？后续版本（1.1.9）可以做成 markdown 批量传入的形式。
2. 目前md只能一个个导入，主要是受限于 embedding 过程是全程本地的，并发十分困难。我这边可以接入embedding在线服务，但是由于需要花钱，我自己也没法承担，可能会收费（几百万字一块钱）。如果后续推出在线版本，能否接受呢？

**Comment by whshang** [comment]
不用专门批量导出，obsidian文件夹结构比较简单就是一堆标准格式的本地md，Msty支持直接监控一整个工作空间，也就是对同目录下.obsidian的隐藏文件夹里面的各类配置文件进行对比，标识目录树更新时间啥的

不监控ob文件夹，手工批量选择，同名的覆盖也行，就是稍微要定期动动手，这样通用性更强一些

批量选择，单线程队列也行，主要是我单个文件不大，但文件数量多（都是几千字的笔记）

在线的话主要考虑还是本地笔记与云端知识库的同步便捷性、内容的安全性，不然我就notion+dify/coze了

**Comment by wizardAEI** [comment]
1.1.9已更新该功能，近期就会上线！

**Comment by whshang** [comment]
Cool, 已经用上了
