### ISSUE TITLE
内存调用过大导致软件自动闪退

### ISSUE THREAD

**Issue by lly0010** [wizardAEI/Gomoon#110]
### 描述错误和预期行为

请简要描述您遇到的问题，以及您期望发生的情况。

### 截图

![image](https://github.com/user-attachments/assets/1007c3d4-1f00-4fc8-98d8-37293cb2cd64)

### 环境信息 (重要⭐️)

- 操作系统：(Mac / Windows) Windows

- 其他特殊环境信息：(例如：使用代理，使用 Docker 等)

### 其他信息

其他您认为相关的信息。

**Comment by wizardAEI** [comment]
哈喽，请问是启用了什么能力了吗？比如记忆胶囊，本地模型。正常情况下软件本身只会占用200-400MB。

**Comment by lly0010** [comment]
都没有就调用了gpt-4o

**Comment by wizardAEI** [comment]
可以看下gpt的配置信息是不是类似于下面的图片，不清楚是否是出现了一些意料之外的问题，可以尝试下重启电脑，升级软件等。如果确实还是不能使用的话，可以尝试下其他桌面应用。带来的不便还请谅解👼
![image](https://github.com/user-attachments/assets/4b3d020a-51a9-47d9-8dcb-612a3fb98db3)
