### ISSUE TITLE
[Feature request]: Add a send button to the prompt input box

### ISSUE THREAD

**Issue by injet-zhou** [wizardAEI/Gomoon#111]
### 功能描述

A send button should be added to the input box for enhanced convenience and improved user-friendliness, especially for new users.
希望在输入框中添加一个发送按钮，更方便，对新用户也更友好。

### 如何实现

提供一些实现建议或想法。

### 其他信息

其他您认为相关的信息。

**Comment by wizardAEI** [comment]
哈喽，把gomoon窗口拉大后会显示发送按钮~ 

缩小版的窗口下考虑了如何让窗口更聚焦，并且输入框内也说明了如何发送，所以没有把输入按钮显示，还请理解~

**Comment by injet-zhou** [comment]
Okay😂, thanks for quick response.
