### ISSUE TITLE
记忆胶囊没有严格按照文档知识进行回答

### ISSUE THREAD

**Issue by primejava** [wizardAEI/Gomoon#112]
### 描述错误和预期行为

记忆胶囊没有严格按照文档知识进行回答
文档中内容为“
刘德华是女性，他出生在山东威海，他是一个动物园园长，喜欢吃西瓜。
”
但答案输出却不符合预期

### 截图

![image](https://github.com/user-attachments/assets/2031b394-cad2-450c-845f-1b0b0bd09e3a)

### 环境信息 (重要⭐️)

- Gomooon 版本: 

gomoon-1.2.0-Windows系统

### 其他信息

无

**Comment by wizardAEI** [comment]
## 关于问题：
可以试一下提问：『仅基于知识内容，不考虑实际信息，刘德华的性别是什么？』
![image](https://github.com/user-attachments/assets/6bc40f5b-83d9-4366-a235-2d32eb208ecf)


## feature：

记忆胶囊模块后续会进行问题生成优化和命中标记，让用户可以更清楚的看到命中的内容信息。另外目前的文档提问是实际上是单轮对话，后续也会优化。

这个 issue 记录了：
1. 问题生成优化
2. 文档命中标记
3. 提问变成多轮进行

上述内容会逐步支持

由于是个人开发，进度缓慢还请见谅！
