### ISSUE TITLE
ctrl+c+c快捷键冲突

### ISSUE THREAD

**Issue by person2217** [wizardAEI/Gomoon#114]
### 功能描述

电脑上ctrl+c+c和goldendict冲突，希望能用户自定义快捷键。

### 如何实现

提供一些实现建议或想法。

### 其他信息

其他您认为相关的信息。

**Comment by person2217** [comment]
感谢

**Comment by wizardAEI** [comment]
哈喽哈喽，感谢提出意见！

这里需要读取用剪贴板，所以ctrl+c是必须的，后续可以改成ctrl+c+特殊键位，但是由于该键位是写死在另外的进程中的，改起来有点麻烦。等最近不忙了我尝试改一下

**Comment by wizardAEI** [comment]
哈喽哈喽，1.2.1版本已经加入该功能啦
