### ISSUE TITLE
模型引擎配置建议

### ISSUE THREAD

**Issue by 441837297** [wizardAEI/Gomoon#115]
### 功能描述

1、希望能增加多个自定义模型，且自定义模型支持重命名。
2、希望Claude支持修改模型名称，因为当Claude API为国内中转API提供时，只能在自定义模型中进行配置，而无法在Claude中配置。
3、希望ChatGPT支持增加模型名称，例如gpt-4o-2024-08-06，gpt-4o-2024-05-13等等，目前只支持gpt-3.5 4o 4o mini三种。

**Comment by 441837297** [comment]
4、如果能增加软件备份功能就更好了，方便在不同电脑上使用同一套模型引擎配置。

**Comment by wizardAEI** [comment]
哈喽哈喽，感谢你的反馈
1. 关于模型自定义问题，由于Gomoon这一模块在设计的时候是一个Map的数据结构，比较难自定义扩展，所以这一部分一直没有更改。
2. Claude国内中转API一般是遵循openAI，但是Claude官方的API是不遵循的，这也就是为什么为什么没有在Claude加入支持修改模型名称，因为很可能你在Claude里配置后也不能使用
3. ChatGPT的可使用模型会根据不同的厂商支持模型不一致而变化，故只支持了最流行和实惠的三个模型
4. 模型备份（或者说配置备份）功能会随着在线版一起推出，包括上述的支持模型少的问题也都会在在线版逐一解决！
最近事情有点多，一直没有更新，中秋后会找时间推出新版本的！

**Comment by shengshimeiyan** [comment]
不支持GML4吗？一直显示没有配置，希望增加一个连通性测试，希望能支持GLM4。

**Comment by wizardAEI** [comment]
已经支持配置多个自定义模型啦😇（1.2.4）
