### ISSUE TITLE
Mermaid预览功能追加后，生成时画面抖动很明显

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#116]
Mermaid预览功能追加后，生成时画面抖动很明显，是否可以默认还是生成Mermaid代码，点击代码块的内部按钮（代码块内部“复制”按钮的位置再追加一个“预览”按钮）后再预览

这样用户可以手动预览，生成时画面不会抖动，也可以直接拷贝代码使用

**Comment by wizardAEI** [comment]
哈喽哈喽，生成动画的频繁抖动已经修复了，会在下一个版本上线

预览按钮的想法很好，后续如果生成效果还是差强人意的话会替换成这种方案！

**Comment by lgc653** [comment]
好的，主要AI生成的Mermaid其实很容易有小的错误，导致根本显示不出来。另外预览功能还可以扩展到HTML之类的代码……

**Comment by wizardAEI** [comment]
哈喽哈喽，1.2.3版本会修复这一问题，最近就会更新。另外『预览功能』确实很好，我目前是直接显示了，后续如果有风险就会切成『预览』选项！

**Comment by lgc653** [comment]
已经更新了，现在很好用，谢谢
