### ISSUE TITLE
ollama的模型支持图片输入

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#117]
ollama现在也有很多模型支持图片理解，比如minicpm-v，但是默认输入时会提示“当前模型不支持图片解析”，其实只要放开这个提示就可以使用，不会造成bug，因为不支持图片理解的模型也可以正常反馈提示“抱歉，我无法直接查看或解析图片内容。”之类的
支持图片理解的模型使用目前的接口就能正常返回（我是用其它支持图片理解的模型先触发，然后切换到ollama再点刷新测试的……）

**Comment by wizardAEI** [comment]
哈喽哈喽，感谢提醒！

可以暂时使用Ollama模型（不是备用模型）选项，这个是支持图片输入的，下一个版本会加上所有的Ollama 选项到白名单
