### ISSUE TITLE
请问能否添加自定义模型上下文摘要

### ISSUE THREAD

**Issue by esp3j0** [wizardAEI/Gomoon#121]
### 功能描述

请问现在有上文摘要吗？还是将整个上文信息通过api发送？如果有摘要的话，能否手动调整摘要模型，否则摘要功能消耗key过快。

### 如何实现

提供一些实现建议或想法。

### 其他信息

其他您认为相关的信息。

**Comment by wizardAEI** [comment]
哈喽哈喽，要实现这个功能，可以先让助手总结上面的内容，后删除之前的所有对话片段😇

**Comment by esp3j0** [comment]
> 哈喽哈喽，要实现这个功能，可以先让助手总结上面的内容，后删除之前的所有对话片段😇

好嘞好嘞
