### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by duanmorningsir** [wizardAEI/Gomoon#122]
### 描述错误和预期行为

最近经常在回答的时候卡住，然后电脑的内存蹭蹭往上涨，占用最多的时候有7G，回答结束内存又降下去了

### 截图

![image](https://github.com/user-attachments/assets/13d51fac-0814-44dd-9328-0b5d0f89b7a5)

### 环境信息 (重要⭐️)

- Gomooon 版本: [1.2.5]
- 调用API：KIMI 32k
- 操作系统：( Windows 11)
### 其他建议
非常喜欢这个APP的小窗口和快捷键调用，希望能做得轻量化一些

**Comment by wizardAEI** [comment]
请问有没有使用记忆胶囊功能？

**Comment by wizardAEI** [comment]
也有可能是上下文过长，我在软件中内嵌的一个token计算模块可能会占用较大内存。这个我想办法解决一下

**Comment by duanmorningsir** [comment]
没有用记忆胶囊，可能是我的聊天太长了，我开了一个新聊天之后就能正常用了

> 也有可能是上下文过长，我在软件中内嵌的一个token计算模块可能会占用较大内存。这个我想办法解决一下

**Comment by wizardAEI** [comment]
有注意到生成很卡的时候已经到多少 k token了吗

**Comment by wizardAEI** [comment]
我这边尝试到了16k仍然没有复现

**Comment by duanmorningsir** [comment]
> 我这边尝试到了16k仍然没有复现

我看了一下聊天记录并不长，大概只有20条，我怀疑是出现问题因为我让他识别了好几张图片，如果要复现的话，可以试试我这几张图片，依次让他识别并回答。API用的是kimi，因为只有kimi的免费API能输入图片
![10-41-33-image](https://github.com/user-attachments/assets/40d22ea0-912c-4c51-829b-fa41de4c0461)
![10-51-25-image](https://github.com/user-attachments/assets/ddf55dcd-f46f-4584-a11d-2a3ebc2cea6a)
![11-00-56-image](https://github.com/user-attachments/assets/b81263b9-bc33-474d-9b3f-5727706d5444)

**Comment by wizardAEI** [comment]
你可以试试，gomoon自带的文字识别

**Comment by duanmorningsir** [comment]
试了，自带的还挺好用，第二、三张那种清晰的基本能识别出来，像第一张图片就无能为力了

**Comment by wizardAEI** [comment]
1.2.6 版本优化了可能会引起该原因的部分☮️
