### ISSUE TITLE
涉及新功能的建议

### ISSUE THREAD

**Issue by Lolisky** [wizardAEI/Gomoon#123]
### 功能描述
自动隐藏不可用的模型，或手动隐藏不常用的模型。例如，我没有文心的api，不常用claude haiku，但这些模型在主界面模型选择列表中排在前面。有可能把用户真正常用的挤在很靠下的位置。
### 如何实现
考虑：a. 在主界面隐藏从未配置api和接口的模型；或
b. 在设置-模型引擎配置-单个模型配置中增加一个”隐藏该模型“的选项。
### 功能描述
在实际使用中，
a. 由于完全没有框线，行与行之间也没有颜色区分，一些复杂表格渲染结果看起来令人困惑；
b. 大模型输出的列数很多的md表格无法渲染为表格；
c. 连续多个表格，如果中间没有空行，渲染后是粘连在一起的。如：
```
**主持人信息**
| 姓名 | 职务 | 主要经历 |
|------|------|----------|
| 张三| 职务1 | 介绍1 |
**拟邀请嘉宾信息**
| 姓名 | 身份/职务 | 主要成就/特点 |
|------|------------|---------------|
| 李四 | 教授 | 研制 |
```
渲染后的效果非常怪。但claude和gemini确实会输出这样的表。
### 如何实现
a. 考虑：通过框线或者内容行颜色一深一浅来改善表格渲染？
b、c：这可能是md扩展语法不统一造成的，我难以判断，不知开发者是否能识别原因？
### 功能描述：
可以临时关闭快速问答快捷键/功能，或者至少在用户正在使用tomoon的设置菜单、编辑对话等内部功能时候不要激活，因误触而打断配置/正在编辑的对话很难受
### 如何实现
设置界面加个开关？
## 功能5：本地错误日志

因为我没有相关知识背景，对此类软件开发也不了解，以上建议仅供您参考。
建议您在github也放一份捐赠链接/二维码？

**Comment by wizardAEI** [comment]
哈喽哈喽，最近我正在给予 Gomoon 积累下来的一些优点开发另一款软件，Gomoon 目前状态处于功能维护，不会再有新功能了~

关于你说的这几点：

1. 模型可选显示： 新软件的模型配置完全是自定义的，无须担心不用的模型会显示
2. markdown表格显示优化：会尝试在 Gomoon 和新软件上优化该功能
3. 改进快速问答的激活逻辑：这个可以尝试在 Gomoon 上改变快捷键，默认 ctrl + c + c 可以改成 ctrl + c + 其他键位
4. 目前 Gomoon 可导出的配置有助手配置，记录，记忆胶囊；新软件是基于配置运行的，天然支持配置导入导出~
5. 本地错误日志：这个确实在 Gomoon 上做的不好，在纠错的时候浪费了很多时间；我认为也是自己缺少独立开发经验导致的，后面会好好反思下这部分怎么做。

非常感谢你的建议😇 后续的开发会持续参考这些功能点来开发的！
