### ISSUE TITLE
openai 的 api 使用无响应

### ISSUE THREAD

**Issue by wongshg** [wizardAEI/Gomoon#13]
在 chatbox 里可以正常调用的 apikey，使用了 baseURL，但是这里无法使用。

**Comment by wizardAEI** [comment]
进群我们一起看一下吧（仓库下方有二维码）

**Comment by wizardAEI** [comment]
没有动态设置baseURL CORS和 Content-Security-Policy，本周内支持，如果有其他朋友遇到这类问题可以来找我单独打包

**Comment by wizardAEI** [comment]
1.0.4版本已经修复
