### ISSUE TITLE
Do you have a 1.0.4 version for Windows platform? thank you！

### ISSUE THREAD

**Issue by kfeng1014** [wizardAEI/Gomoon#18]

**Comment by wizardAEI** [comment]
Thank you for your attention! I am currently working on adding the check for updates feature, but I have encountered some issues. Once resolved, the 1.0.4 version will be released on all three platforms simultaneously.  

感谢你的关注！目前我正在增加自动检查更新的功能，但是现在遇到了一些问题，解决后会一起在三端发布1.0.4版本的

**Comment by kfeng1014** [comment]
Thank you for your hard work. I will continue to follow and support the Gomoon project.
![012E9761](https://github.com/wizardAEI/Gomoon/assets/144030689/d8ad478b-a249-4909-90fe-8c467b425d61)
