### ISSUE TITLE
复制文字时会自动朗读

### ISSUE THREAD

**Issue by RinSky123** [wizardAEI/Gomoon#32]
如题，不仅会自动朗读还会重复朗读，关闭应用会停止播报，其他应用没有遇到此问题

**Comment by wizardAEI** [comment]
请问Gomoon版本号和电脑系统是什么？

**Comment by wizardAEI** [comment]
感谢反馈！已经重新打包了windows版本，在release处重新下载就可以了😇（抱歉不能直接使用软件内更新功能，因为同属于1.0.5版本，需要重新下载并替换）

**Comment by RinSky123** [comment]
> 感谢反馈！已经重新打包了windows版本，在release处重新下载就可以了😇（抱歉不能直接使用软件内更新功能，因为同属于1.0.5版本，需要重新下载并替换）

好的谢谢
