### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by RinSky123** [wizardAEI/Gomoon#36]
请问是否可以在手动复制内容时让对话界面跟着鼠标滚动呢？
目前的情况是复制时如果还想复制下面的内容的话就会直接给我全部选中了

**Comment by wizardAEI** [comment]
好的，这个优化确实可以为用户提供很多便利，我尝试一下🚀。

**Comment by RinSky123** [comment]
> 好的，这个优化确实可以为用户提供很多便利，我尝试一下🚀。

期待大佬的新版本

**Comment by wizardAEI** [comment]
因为监听联动起来还是挺多的，暂时用了一个比较偷懒的方法，让对话不再是横穿整个页面了，后面版本会持续优化使用细节。
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/946ac2df-5932-4547-9811-cefa6681364e)

**Comment by RinSky123** [comment]
> 因为监听联动起来还是挺多的，暂时用了一个比较偷懒的方法，让对话不再是横穿整个页面了，后面版本会持续优化使用细节。 ![image](https://private-user-images.githubusercontent.com/61337085/305100954-946ac2df-5932-4547-9811-cefa6681364e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTMxNTEsIm5iZiI6MTcwODAxMjg1MSwicGF0aCI6Ii82MTMzNzA4NS8zMDUxMDA5NTQtOTQ2YWMyZGYtNTkzMi00NTQ3LTk4MTEtY2VmYTY2ODEzNjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZTY1YzM0MjQzNzlmMzI5OThiYWJhNWY5NDMxN2UyMGE3MjJlZTg0ZjhhNzk1M2UyNmY0MjMxODBlYjlhZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YF9fSoDXT5pABVtzZGnbTaCg1UslXXwVAj6lTU3uUVs)

这样的话界面还变好看了，非常可以

**Comment by wizardAEI** [comment]
感谢理解😇，新版本本周内就会上线🚀🚀🚀
