### ISSUE TITLE
bug和建议

### ISSUE THREAD

**Issue by RinSky123** [wizardAEI/Gomoon#47]
v1.0.6bug：目前版本无法发送文件让ai进行解析
建议：建议可以在发送文件的同时输入文字说明，还有加一个文件拖拽窗口并弹窗是否要编写文字说明并发送此文件？或者是拖拽后直接放在输入框里，然后编辑文字发送

**Comment by RinSky123** [comment]
还有个建议就是保存对话，如果是在之前对话的基础上保存的，建议直接合并成一个对话，不要分开保存了

**Comment by wizardAEI** [comment]
> v1.0.6bug：目前版本无法发送文件让ai进行解析 建议：建议可以在发送文件的同时输入文字说明，还有加一个文件拖拽窗口并弹窗是否要编写文字说明并发送此文件？或者是拖拽后直接放在输入框里，然后编辑文字发送

哈喽，我这边是可以正常发送文件的，再试一下呢？
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/cdb44325-5fda-4ca5-ae3d-3fd927585e60)

另外发送文件和保存对话的交互形式还在探索，单纯直接合并历史也可能造成一些问题，这个我再想想如何交互更友好一些。

**Comment by RinSky123** [comment]
我发现除了docx格式文档外，pdf，txt等格式都可以正常发送，发doc格式提示让我转为docx格式，但是docx格式无法正常发送也没有任何提醒





------------------ 原始邮件 ------------------
发件人: aei ***@***.***&gt;
发送时间: 2024年3月4日 14:57
收件人: wizardAEI/Gomoon ***@***.***&gt;
抄送: Fireworks ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wizardAEI/Gomoon] bug和建议 (Issue #47)

**Comment by wizardAEI** [comment]
非常感谢你细致的测试！docx类型无法使用，排查发现是未显式使用的依赖没有被安装。
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/728778ff-df51-4ba1-9d01-4907f876483f)
今晚会更新版本来修复！

**Comment by RinSky123** [comment]
> 非常感谢你细致的测试！docx类型无法使用，排查发现是未显式使用的依赖没有被安装。 ![image](https://private-user-images.githubusercontent.com/61337085/309673057-728778ff-df51-4ba1-9d01-4907f876483f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjA2ODIsIm5iZiI6MTcwOTU2MDM4MiwicGF0aCI6Ii82MTMzNzA4NS8zMDk2NzMwNTctNzI4Nzc4ZmYtZGY1MS00YmExLTlkMDEtNDkwN2Y4NzY0ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEzNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYjRjMzkxMTk1NTMwOGY3YWFkYWIyY2FhOWIxNGI2ODNlNzJhNDRiMDVmYjM2ODU1N2FkZGE3YjYyNGI2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWUe7EDUk2tZThz-DmW2CcHKw0ty_donUGVyqo4Wq3w) 今晚会更新版本来修复！

好的，新版能发这里吗，官网下太慢了，应用内更新更下不动

**Comment by wizardAEI** [comment]
> 不动

可以加一下QQ群，艾特我发给你最新的对应系统版本。 不放在github主要是因为我本地的VPN不是很稳定，经常上传一半就fail了☹️

**Comment by RinSky123** [comment]
> > 不动
> 
> 可以加一下QQ群，艾特我发给你最新的对应系统版本。 不放在github主要是因为我本地的VPN不是很稳定，经常上传一半就fail了☹️

麻了
