### ISSUE TITLE
一些功能建议！！！！！

### ISSUE THREAD

**Issue by Stanley-baby** [wizardAEI/Gomoon#53]
1. 希望可以加入 gemini 模型（因为免费），并且带自定义地址（可以通过反代突破地域限制）
2. Mac 端希望可以把应用窗口添加到屏幕上方状态栏，使用更加快捷方便
**示例：**

https://github.com/wizardAEI/Gomoon/assets/58399659/6bc3a880-97de-4db4-aab8-3a2254be093c

**Comment by wizardAEI** [comment]
感谢您的建议！
1. 增加厂商和对应的高级设置（如温度等）目前正在做，下个版本就会加上
2. 我还是更想走快捷键的方式，现在使用快捷键快速唤醒后（默认是cmd+G），默认光标是focus在输入框上的，这样几乎不用鼠标操作就可以完成一整套操作，体验还是挺好的。

Uploading Screen Recording 2024-03-10 at 13.23.38.mov…

**Comment by wizardAEI** [comment]
> 感谢您的建议！
> 
> 1. 增加厂商和对应的高级设置（如温度等）目前正在做，下个版本就会加上
> 2. 我还是更想走快捷键的方式，现在使用快捷键快速唤醒后（默认是cmd+G），默认光标是focus在输入框上的，这样几乎不用鼠标操作就可以完成一整套操作，体验还是挺好的。
> 
> Uploading Screen Recording 2024-03-10 at 13.23.38.mov…


https://github.com/wizardAEI/Gomoon/assets/61337085/ed03bb32-5dca-4a9d-b218-55b113934584
