### ISSUE TITLE
百度的能否自定义模型的api

### ISSUE THREAD

**Issue by Junffzz** [wizardAEI/Gomoon#57]
百度有很多不同模型，好像api不同，想自定义创建不同的模型

**Comment by wizardAEI** [comment]
哈喽，下一个版本GPT已经支持自定义模型，百度模型由于每一个模型的URL都不一致，langchain都没有支持。
暂时只能调用主流大模型，之前我在langchain中加入了百度最新的ERNIE-Speed-128K和ERNIE-Speed-8K并提供了ERNIE-Speed-128K的模型，希望能一定程度上解决你的问题！
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/75717965-d717-4010-b6a1-0c6d306eda3f)

**Comment by Junffzz** [comment]
> 哈喽，下一个版本GPT已经支持自定义模型，百度模型由于每一个模型的URL都不一致，langchain都没有支持。 暂时只能调用主流大模型，之前我在langchain中加入了百度最新的ERNIE-Speed-128K和ERNIE-Speed-8K并提供了ERNIE-Speed-128K的模型，希望能一定程度上解决你的问题！ <img alt="" width="35%" height="35%" src="https://private-user-images.githubusercontent.com/61337085/316225984-75717965-d717-4010-b6a1-0c6d306eda3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTAzNjQsIm5iZiI6MTcxMTI1MDA2NCwicGF0aCI6Ii82MTMzNzA4NS8zMTYyMjU5ODQtNzU3MTc5NjUtZDcxNy00MDEwLWI2YTEtMGM2ZDMwNmVkYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAzMTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTM1ZTdjNmI2NzY0YjBhNmFhYzY5OGQyYjcyNTI3ZTkzNzAwZmRmNThmODhhMzhiNWMxYjJiZGJjYzI5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ls8pl_Ldo7BGcixEETMosGurD0SImeeQU1GPOwtr4As">

为什么我这儿下载的版本没有你这些模型？
<img width="386" alt="image" src="https://github.com/wizardAEI/Gomoon/assets/27394594/1d25f3af-2075-4533-964e-3ff0f43796db">

**Comment by wizardAEI** [comment]
版本还没有推送，目前还有几个问题没有解决(主要是本地模型和链接解析9优化)。
新版本也会更新语音合成功能，预计四月初会开发完！

**Comment by wizardAEI** [comment]
新版本差不多开发完了，周末会打包出新版本(1.0.8)
