### ISSUE TITLE
Prompt 模板最好能支持变量

### ISSUE THREAD

**Issue by Junffzz** [wizardAEI/Gomoon#58]
比如百度的prompt如下：
现在你是一位精通{code}的资深IT研发工程师，你需要解答{problem}这个问题。注意你需要介绍问题所涉及的计算机原理并给出示例帮助我更清晰的理解这个问题。
模板ID：
pt-d1bfe25ca48d0511
场景类型：文生文
参数格式：大括号{}

**Comment by wizardAEI** [comment]
有这方面的打算，后续会先在问答助手上尝试加入变量功能

**Comment by wizardAEI** [comment]
最近有些新的想法，会在一个全新版本中实现该能力，且配置和流程更自由一些，先去挖坑了！
