### ISSUE TITLE
中文识别效果好像不太好，不知道能不能更新成为对中文识别相对较好的模型做本地ocr

### ISSUE THREAD

**Issue by mumutoy** [wizardAEI/Gomoon#66]
比如：https://github.com/sml2h3/ddddocr  （py版本） https://github.com/J3n5en/ddddocr-js  （node版）
或者是百度Paddle，https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/README_cn.md ？

**Comment by wizardAEI** [comment]
👌👌

**Comment by wizardAEI** [comment]
我在线尝试了一下百度Paddle，占用内存太高（16g内存到了98%且无响应）。本地使用开发环境启动失败，引用包模块报错。且ddddocr和paddle长期没有更新了，不太确定后续会不会继续维护。最终还是决定先保持现状，后续有更好的国产开源替代再升级吧🥲
附：当前使用的依赖更新和下载量状况和paddle的对比：
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/50e2c770-645c-4626-8715-cdcad7279e1c)
![image](https://github.com/wizardAEI/Gomoon/assets/61337085/6ab2dc84-040c-49d4-9769-8a28598419e8)
