### ISSUE TITLE
import icon from '../../resources/icon.png?asset' 报错

### ISSUE THREAD

**Issue by tufeiping** [wizardAEI/Gomoon#8]
拉取后，编译报错，提示找不到 resources 资源，查看仓库，没有提交这个目录？

**Comment by wizardAEI** [comment]
是的，这个是一个静态资源目录，内容可以在安装后的app中找到。如果嫌麻烦也可以进群cue我，发给你对应的资源。

**Comment by tufeiping** [comment]
没事，我下载安装后，拷贝过来了
