### ISSUE TITLE
希望支持 讯飞星火大模型

### ISSUE THREAD

**Issue by Allenxuxu** [wizardAEI/Gomoon#91]

**Comment by wizardAEI** [comment]
讯飞模型可以使用下个版本的自定义模型去调用，自定义模型支持所有可以适配OPENAI接口的模型，包括讯飞，豆包，DeepSpeak等等，预计这周末会更新

**Comment by wizardAEI** [comment]
mac 版本已经支持了自定义模型，win 预计周末 1.1.5 版本会发布出来
