### ISSUE TITLE
gemini-1.5-pro-latest也支持解析图片文件，但是软件目前不允许提交图片

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#95]
gemini-1.5-pro-latest也支持解析图片文件，但是软件目前不允许提交图片

**Comment by wizardAEI** [comment]
我后续看下实现方案 如果可以加上的话，周末的新版本1.1.6会支持

**Comment by wizardAEI** [comment]
1.1.6版本已更新
![image](https://github.com/user-attachments/assets/5e6a6268-e12c-4fdd-bd46-a6aab3368418)

**Comment by lgc653** [comment]
太感谢了
