### ISSUE TITLE
使用文心一言模型时提示Open api daily request limit reached

### ISSUE THREAD

**Issue by lgc653** [wizardAEI/Gomoon#97]
非常感谢如此优秀的作品
使用文心一言模型时提示Open api daily request limit reached
好像是要开通“在线服务”，但是不知道你默认用的哪个模型（我开通的是ERNIE-3.5-8K），如果能和chatgpt一样定义模型就更好了

**Comment by wizardAEI** [comment]
文心3默认使用的是ERNIE-Speed-8K，文心4使用的是ERNIE-Bot-4。这里确实提示不友好，下个版本会尝试优化

**Comment by wizardAEI** [comment]
另外这里的提示 Open api daily request limit reached，应该是日常访问超过限制了，可以看一下千帆平台的配置中是否有相关的限制提醒

**Comment by lgc653** [comment]
就是我没有开通ERNIE-Speed-8K的“在线服务”问题，已经可以使用了，建议给个提示，或者可以让用户自定义模型。
产品做得很好，非常感谢

**Comment by wizardAEI** [comment]
哈喽，1.1.7版本已更新，目前已上架mac版本，预计周一会上架win版本👼
