### ISSUE TITLE
希望能够添加多个自定义模型

### ISSUE THREAD

**Issue by Wooden-Gear** [wizardAEI/Gomoon#98]
希望能够添加多个自定义模型，以便来回切换，毕竟导入添加记忆胶囊太费token了，得用便宜点的模型。

**Comment by wizardAEI** [comment]
感谢建议！关于更灵活的定义模型功能，受到早期的设计架构影响，目前的模型管理不是很灵活，正在尝试优化。

**Comment by Wooden-Gear** [comment]
@wizardAEI 请问记忆胶囊仅仅是用AI整理了一下文件，还是建立了一个向量数据库啊？

**Comment by wizardAEI** [comment]
建立了一个本地向量数据库，embedding 模型见 https://jina.ai/embeddings

**Comment by wizardAEI** [comment]
哈喽，权衡了一下，后续还是采用增加模型类型的方案来支持该需求吧~ 1.17版本已经将DeepSeek单独拎出来了，如果需要其他模型如果有的话也可以留言！
